### ISSUE TITLE
How can I keep widget's status?

### ISSUE THREAD

**Issue by lakerszhy** [bizz84/page_flip_builder#1]
Each time flips, the widget will be disposed.
I want to flip between a map view and a listview, this make map view to be disposed everytime.
Thank you.

**Comment by bizz84** [comment]
@lakerszhy You could preserve the state of a widget by setting a `GlobalKey` in the parent widget that contains the `PageFlipBuilder`.

Note that you can preserve the state, but your widgets will still rebuild every time the value of the internal `AnimatedController` changes. If it is expensive to rebuild a map view, then this will be a problem for you.

There may be a workaround that involves using an `AnimatedSwitcher` rather than an `AnimatedController` to control the animation. This will be better for performance but you'll have to give up the "interactive dragging" functionality.

This article explains this approach (though the implementation is not perfect):

https://medium.com/flutter-community/flutter-flip-card-animation-eb25c403f371

**Comment by lakerszhy** [comment]
Thank you, I will try it.
